### ISSUE TITLE
funopen issue

### ISSUE THREAD

**Issue by TheFausap** [carld/micro-lisp#22]
Hello,
I know it could sound weird, but how could be possible to rewrite the eval_string function without using funopen?
I totally rewrote the source code in K&R style, porting mlisp89 to a CPM/80 using Aztec C compiler.
I got two issues, at the linking time: the first one with strdup (easily fixed), the other one with funopen, but I think it's quite hard to implement.
So if you could give me a hint, it would great.
thanks

**Comment by carld** [comment]
Hey, that sounds awesome I'd love to see the rewrite. 
`funopen` is used to return a FILE* to a block of memory, such that any reads will return data from memory, instead of the usual file on disk. In this case ultimately so that the likes of `getc` work the same whether the source be file or memory.
The only thought I have right now, is to implement wrappers for all the FILE * functions, such as fopen, funopen, getc, fprint etc, based on a struct and functions that check the struct and use the appropriate functions either to read from file or memory.

```
struct MEM_OR_FILE {
  enum { MEMORY_STREAM, FILE_STREAM } type;
  struct {
    FILE * fp;
  } file;
  structure {
    unsigned char *memory;
    int fgetc(MEM_OR_FILE *);
    int fread(MEM_OR_FILE *, ...);
  } memory;
};

MEM_OR_FILE * mfopen(const char *filename, ...) {
  MEM_OR_FILE *mf = malloc(sizeof (MEM_OR_FILE));
  mf->type = FILE_STREAM;
  mf->file->fp = fopen(filename, ...);
  return mf;
}

MEM_OR_FILE *mfunopen(char *memory, int (*mfgetc) (MEM_OR_FILE *), ...) {
  MEM_OR_FILE *mf = malloc(sizeof (MEM_OR_FILE));
  mf->type = MEMORY_STREAM;
  mf->memory->memory = memory;
  mf->memory->fgetc = mfgetc;
  return mf;
}

int mfgetc(MEM_OR_FILE *mf) {
  return *mf->memory->memory++;
}

```

This is basically implementing all that stuff that lives under funopen and FILE *, but maybe other ways to make it less onerous with macros or something...

**Comment by TheFausap** [comment]
Thanks a lot!
So when you call, in the code, funopen with freadmem as callback function for read operation, I should use this mfunopen. 
But I'm a little confused when you use getc in lookahead function. In that case, which function I should use?

**Comment by carld** [comment]
getc would have to be replaced with a mfgetc or similar that took the MEM_OR_FILE structure and uses either the file or the memory accordingly.

**Comment by carld** [comment]
Something like:
```
int mfgetc(MEM_OR_FILE *mf) {
  if (mf->type == FILE_STREAM) {
    return getc(mf->file->fp);
  } else (mf->type == MEMORY_STREAM) {
    return * mf->memory->memory++ ;
  }

}

```

**Comment by TheFausap** [comment]
oh, thanks! now it's clear. I'm struggling right now with the env variable, because it seems too large for 63KB of RAM :)
